markdown: redcarpet
highlighter: null
permalink: /:title

url: http://puyuan.github.io/weblog
baseurl: /weblog

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed