markdown: redcarpet
highlighter: null
permalink: /:title

url: http://puyuan.github.io
baseurl: 

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
gems:
  - jekyll-sitemap
